service: backend-sls
frameworkVersion: '>=4.0.0'

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: dev
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_SERVICE_ROLE_KEY: ${env:SUPABASE_SERVICE_ROLE_KEY}
    USE_DB_MOCK: ${env:USE_DB_MOCK}
    API_KEY: ${env:API_KEY}
    WEBPAY_COMMERCE_CODE: ${env:WEBPAY_COMMERCE_CODE, ''}
    WEBPAY_API_KEY: ${env:WEBPAY_API_KEY, ''}
    WEBPAY_HOST: ${env:WEBPAY_HOST, ''}
   
  httpApi:
    cors:
      allowedOrigins:
        - '*'                # todos los orígenes
      allowedHeaders:
        - '*' 
      allowedMethods:
        - '*'  
      allowCredentials: false
      
functions:
  - ${file(./routes/partidos/serverlessPartidos.yml)}
  - ${file(./routes/jugadores/serverlessJugadores.yml)}
  - ${file(./routes/calificaciones/serverlessCalificaciones.yml)}
  - ${file(./routes/tenderbot/serverlessTenderBot.yml)}

plugins:
  - serverless-offline
  

package:
  individually: true
  exclude:
    - node_modules/**
    - .serverless/**
    - .webpack/**
    - logs/**
    - tmp/**
    - data/**
    - "**/*.map"
    - "**/*.zip"
    - "**/*.md"
    - "**/*.log"




build:
  esbuild:
    bundle: true
    minify: true
    target: node22
    platform: node
    external: 
      - util
      - crypto
      - stream
      - http
      - https
      - url
      - zlib
      - transbank-sdk

custom:
  serverless-offline:
    disableCookieValidation: true
      
