service: backend-sls
frameworkVersion: '>=4.0.0'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_SERVICE_ROLE_KEY: ${env:SUPABASE_SERVICE_ROLE_KEY}
    USE_DB_MOCK: ${env:USE_DB_MOCK}
    API_KEY: ${env:API_KEY}

  # Esto aplica solo en AWS, no afecta a serverless-offline
  apiGateway:
    apiKeys:
      - name: FplayChileApiKey
        value: ${env:API_KEY}

  httpApi:
    cors:
      allowedOrigins:
        - '*'                # todos los orígenes
      allowedHeaders:
        - Content-Type
        - X-Api-Key
        - Authorization
        - X-Requested-With
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: false


functions:


  - ${file(./routes/login/serverlessLogin.yml)}
  - ${file(./routes/partidos/serverlessPartidos.yml)}
  - ${file(./routes/jugadores/serverlessJugadores.yml)}
  - ${file(./routes/swagger/serverlessSwagger.yml)}

plugins:
  - serverless-offline

package:
  individually: true
  exclude:
    - .git/**
    - test/**
    - docs/**
    - .env
    - README.md
    - awscliv2.zip

custom:
  esbuild:
    bundle: true
    minify: true
    target: node20
    platform: node
    external:
      - aws-sdk
      
